/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import Metodos.MetodosBD;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Shape;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author Alvaro Becker
 */
public class Error extends javax.swing.JFrame {

    int xMouse, yMouse;

    class RoundedBorder implements Border {

        private int radius;

        RoundedBorder(int radius) {
            this.radius = radius;
        }

        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
        }

        public boolean isBorderOpaque() {
            return true;
        }

        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }
    }
    JFrame framep2;
    JFrame framep;

    /**
     * Creates new form Empty
     * @param contenido
     * @param frame
     * @param frame2
     */
    public Error(String contenido, JFrame frame, JFrame frame2) {
        initComponents();
        Mensaje2.setVisible(false);
        Mensaje2.setFocusable(false);
        Mensaje2.setEnabled(false);
        framep = frame;
        framep2 = frame2;
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, getBounds().width, getBounds().height, 20, 20);
        setShape(forma);
        fondo.setBorder(Metodos.MetodosFront.setRoundedborder(20, new Color(117, 170, 250), true, new Color(117, 170, 250)));
        fondo.setOpaque(false);
        contenedor.setBorder(Metodos.MetodosFront.setRoundedborder(20, Color.WHITE, true, Color.WHITE));
        contenedor.setOpaque(false);
        pnlconfirmar.setBorder(Metodos.MetodosFront.setRoundedborder(20, new Color(8, 68, 164), true, new Color(8, 68, 164)));
        pnlconfirmar.setOpaque(false);
        framep.setEnabled(false);
        framep.setFocusable(false);
        try {
            framep2.setEnabled(false);
            framep2.setFocusable(false);
        } catch (Exception e) {
        }
        Mensaje.setText(contenido);
        jScrollPane1.setVisible(false);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        if (contenido.length() > 40) {
            jScrollPane1.setVisible(true);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
            Mensaje.setEnabled(false);
            Mensaje.setVisible(false);
            Mensaje.setFocusable(false);
            Mensaje2.setVisible(true);
            Mensaje2.setFocusable(true);
            Mensaje2.setEnabled(true);
            Mensaje2.setText(contenido);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sup = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        pnlconfirmar = new javax.swing.JPanel();
        lblconfirmar = new javax.swing.JLabel();
        Mensaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensaje2 = new javax.swing.JTextArea();
        borde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sup.setOpaque(false);
        sup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                supMouseDragged(evt);
            }
        });
        sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supMousePressed(evt);
            }
        });

        javax.swing.GroupLayout supLayout = new javax.swing.GroupLayout(sup);
        sup.setLayout(supLayout);
        supLayout.setHorizontalGroup(
            supLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        supLayout.setVerticalGroup(
            supLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 20));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlconfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblconfirmar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblconfirmar.setForeground(new java.awt.Color(255, 255, 255));
        lblconfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblconfirmar.setText("Confirmar");
        lblconfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblconfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblconfirmarMouseClicked(evt);
            }
        });
        pnlconfirmar.add(lblconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        contenedor.add(pnlconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, 50));

        Mensaje.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        Mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mensaje.setText("Error");
        contenedor.add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 380, 100));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        Mensaje2.setEditable(false);
        Mensaje2.setColumns(15);
        Mensaje2.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Mensaje2.setLineWrap(true);
        Mensaje2.setRows(5);
        Mensaje2.setEnabled(false);
        Mensaje2.setFocusable(false);
        jScrollPane1.setViewportView(Mensaje2);

        contenedor.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 380, 100));

        fondo.add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 420, 270));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        borde.setText("jLabel2");
        getContentPane().add(borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int i = 0;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            i = evt.getKeyCode();
        }
        if (i == KeyEvent.VK_ENTER) {
            framep.setEnabled(true);
            framep.setFocusable(true);
            framep2.setEnabled(true);
            framep2.setFocusable(true);
            dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void supMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_supMouseDragged

    private void supMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_supMousePressed

    private void lblconfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblconfirmarMouseClicked
        framep.setEnabled(true);
        framep.setFocusable(true);
        try{framep2.setEnabled(true);
        framep2.setFocusable(true);}
        catch(Exception e){
        
        }
        dispose();
        //MetodosBD.ConexionOracle conn = new MetodosBD.ConexionOracle();

    }//GEN-LAST:event_lblconfirmarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Error.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Error("Error, Vuelva a Intentarlo", null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JTextArea Mensaje2;
    private javax.swing.JLabel borde;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblconfirmar;
    private javax.swing.JPanel pnlconfirmar;
    private javax.swing.JPanel sup;
    // End of variables declaration//GEN-END:variables
}
