/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author Alvaro Becker
 */
public class Roles extends javax.swing.JFrame {

    int xMouse, yMouse;
    String string;
    JFrame framep;
    Metodos.MetodosBD.ConexionOracle conn;
    JTable table;
    /**
     * Creates new form Roles
     * @param obj
     * @param con
     */
    public Roles(Object[] obj, Metodos.MetodosBD.ConexionOracle con) {
        initComponents();
        conn=con;
        table=(JTable) obj[2];
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, getBounds().width, getBounds().height, 20, 20);
        setShape(forma);
        this.setComponentZOrder(labelFondo, 0);
        labelFondo.setBorder(Metodos.MetodosFront.setRoundedborder(20, Color.BLACK, false, null));
        labelFondo.setFocusable(false);
        labelFondo.setEnabled(false);
        
        if (obj[0].equals("crear")) {
            rol_fondo_crear_pnl.setVisible(true);
            rol_fondo_crear_pnl.setFocusable(true);
            rol_fondo_crear_pnl.setEnabled(true);
            rol_editar_pnl.setVisible(false);
            rol_editar_pnl.setFocusable(false);
            rol_editar_pnl.setEnabled(false);
        } else {
            rol_fondo_crear_pnl.setVisible(false);
            rol_fondo_crear_pnl.setFocusable(false);
            rol_fondo_crear_pnl.setEnabled(false);
            rol_editar_pnl.setVisible(true);
            rol_editar_pnl.setFocusable(true);
            rol_editar_pnl.setEnabled(true);
            
            editrol_casilla_insertar_tf.setText((String) obj[3]);
            
        }
        framep = (JFrame) obj[1];
        framep.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rol_fondo_principal_pnl = new javax.swing.JPanel();
        panelsup = new javax.swing.JPanel();
        Exit8 = new javax.swing.JLabel();
        rol_fondo_crear_pnl = new javax.swing.JPanel();
        rol_titulo_crear_lbl = new javax.swing.JLabel();
        rol_subtitulo_detalle_lbl = new javax.swing.JLabel();
        rol_subtitulo3_rolname_lbl = new javax.swing.JLabel();
        rol_casilla_insertar_tf = new javax.swing.JTextField();
        rol_separador_separa_spt = new javax.swing.JSeparator();
        rol_btn_guardar_pnl = new javax.swing.JPanel();
        rol_btn_guardar_lbl_bloq = new javax.swing.JLabel();
        rol_btn_guardar_lbl = new javax.swing.JLabel();
        rol_btn_cancelar_pnl = new javax.swing.JPanel();
        rol_btn_caneclar_lbl = new javax.swing.JLabel();
        rol_editar_pnl = new javax.swing.JPanel();
        editrol_contenedor_crear_pnl = new javax.swing.JPanel();
        editrol_titulo_editar_lbl = new javax.swing.JLabel();
        editrol_subtitulo_detalle_lbl = new javax.swing.JLabel();
        editrol_subtitulo2_rolname_lbl = new javax.swing.JLabel();
        editrol_casilla_insertar_tf = new javax.swing.JTextField();
        editrol_separador_separa_spt = new javax.swing.JSeparator();
        editrol_btn_cancelar_pnl = new javax.swing.JPanel();
        editrol_btn_caneclar_lbl = new javax.swing.JLabel();
        editrol_btn_guardar_pnl = new javax.swing.JPanel();
        editrol_btn_guardar_lbl = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(530, 245));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rol_fondo_principal_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsup.setBackground(new java.awt.Color(255, 255, 255));
        panelsup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelsupMouseDragged(evt);
            }
        });
        panelsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelsupMousePressed(evt);
            }
        });
        panelsup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Exit8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit8.setText("X");
        Exit8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit8MouseClicked(evt);
            }
        });
        Exit8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Exit8KeyPressed(evt);
            }
        });
        panelsup.add(Exit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 0, 25, 25));

        rol_fondo_principal_pnl.add(panelsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 25));

        rol_fondo_crear_pnl.setBackground(new java.awt.Color(255, 255, 255));
        rol_fondo_crear_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rol_titulo_crear_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rol_titulo_crear_lbl.setText("Crear Rol Empresarial");
        rol_fondo_crear_pnl.add(rol_titulo_crear_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 19, -1, -1));

        rol_subtitulo_detalle_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rol_subtitulo_detalle_lbl.setText("Detalles");
        rol_fondo_crear_pnl.add(rol_subtitulo_detalle_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 57, -1, -1));

        rol_subtitulo3_rolname_lbl.setText("Nombre del Rol");
        rol_fondo_crear_pnl.add(rol_subtitulo3_rolname_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 104, -1, -1));

        rol_casilla_insertar_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rol_casilla_insertar_tfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rol_casilla_insertar_tfKeyReleased(evt);
            }
        });
        rol_fondo_crear_pnl.add(rol_casilla_insertar_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 126, 243, 40));

        rol_separador_separa_spt.setOrientation(javax.swing.SwingConstants.VERTICAL);
        rol_fondo_crear_pnl.add(rol_separador_separa_spt, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 0, 10, 210));

        rol_btn_guardar_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rol_btn_guardar_lbl_bloq.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rol_btn_guardar_lbl_bloq.setText("Guardar");
        rol_btn_guardar_lbl_bloq.setEnabled(false);
        rol_btn_guardar_lbl_bloq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rol_btn_guardar_lbl_bloqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rol_btn_guardar_lbl_bloqMouseEntered(evt);
            }
        });
        rol_btn_guardar_pnl.add(rol_btn_guardar_lbl_bloq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        rol_btn_guardar_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rol_btn_guardar_lbl.setText("Guardar");
        rol_btn_guardar_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rol_btn_guardar_lblMouseClicked(evt);
            }
        });
        rol_btn_guardar_pnl.add(rol_btn_guardar_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        rol_fondo_crear_pnl.add(rol_btn_guardar_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 100, 30));

        rol_btn_cancelar_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rol_btn_caneclar_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rol_btn_caneclar_lbl.setText("Cancelar");
        rol_btn_caneclar_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rol_btn_caneclar_lblMouseClicked(evt);
            }
        });
        rol_btn_cancelar_pnl.add(rol_btn_caneclar_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        rol_fondo_crear_pnl.add(rol_btn_cancelar_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, 30));

        rol_fondo_principal_pnl.add(rol_fondo_crear_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 530, 220));

        rol_editar_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editrol_contenedor_crear_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editrol_titulo_editar_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editrol_titulo_editar_lbl.setText("Editar Rol Empresarial");
        editrol_contenedor_crear_pnl.add(editrol_titulo_editar_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 19, 243, -1));

        editrol_subtitulo_detalle_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editrol_subtitulo_detalle_lbl.setText("Detalles");
        editrol_contenedor_crear_pnl.add(editrol_subtitulo_detalle_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 57, -1, -1));

        editrol_subtitulo2_rolname_lbl.setText("Nuevo Nombre de Rol");
        editrol_contenedor_crear_pnl.add(editrol_subtitulo2_rolname_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 104, -1, -1));

        editrol_casilla_insertar_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editrol_casilla_insertar_tfActionPerformed(evt);
            }
        });
        editrol_casilla_insertar_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editrol_casilla_insertar_tfKeyReleased(evt);
            }
        });
        editrol_contenedor_crear_pnl.add(editrol_casilla_insertar_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 126, 243, 40));

        editrol_separador_separa_spt.setOrientation(javax.swing.SwingConstants.VERTICAL);
        editrol_contenedor_crear_pnl.add(editrol_separador_separa_spt, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 6, 10, 210));

        editrol_btn_cancelar_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editrol_btn_caneclar_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editrol_btn_caneclar_lbl.setText("Cancelar");
        editrol_btn_caneclar_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editrol_btn_caneclar_lblMouseClicked(evt);
            }
        });
        editrol_btn_cancelar_pnl.add(editrol_btn_caneclar_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        editrol_contenedor_crear_pnl.add(editrol_btn_cancelar_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, 30));

        editrol_btn_guardar_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editrol_btn_guardar_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editrol_btn_guardar_lbl.setText("Guardar");
        editrol_btn_guardar_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editrol_btn_guardar_lblMouseClicked(evt);
            }
        });
        editrol_btn_guardar_pnl.add(editrol_btn_guardar_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        editrol_contenedor_crear_pnl.add(editrol_btn_guardar_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 100, 30));

        rol_editar_pnl.add(editrol_contenedor_crear_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 220));

        rol_fondo_principal_pnl.add(rol_editar_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 530, 220));

        getContentPane().add(rol_fondo_principal_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 245));
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 245));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editrol_casilla_insertar_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editrol_casilla_insertar_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editrol_casilla_insertar_tfActionPerformed

    private void Exit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit8MouseClicked
        framep.setEnabled(true);
        dispose();
    }//GEN-LAST:event_Exit8MouseClicked

    private void Exit8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Exit8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit8KeyPressed

    private void panelsupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsupMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelsupMouseDragged

    private void panelsupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsupMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelsupMousePressed

    private void rol_btn_caneclar_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rol_btn_caneclar_lblMouseClicked
        framep.setEnabled(true);
        dispose();
    }//GEN-LAST:event_rol_btn_caneclar_lblMouseClicked

    private void editrol_btn_caneclar_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editrol_btn_caneclar_lblMouseClicked
       framep.setEnabled(true);
       dispose();
    }//GEN-LAST:event_editrol_btn_caneclar_lblMouseClicked

    private void editrol_casilla_insertar_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editrol_casilla_insertar_tfKeyReleased
        
    }//GEN-LAST:event_editrol_casilla_insertar_tfKeyReleased

    private void rol_casilla_insertar_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rol_casilla_insertar_tfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rol_casilla_insertar_tfKeyPressed

    private void rol_casilla_insertar_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rol_casilla_insertar_tfKeyReleased
        boolean repetidorol= conn.RolRep(rol_casilla_insertar_tf);
        if (repetidorol) {
            rol_btn_guardar_lbl_bloq.setVisible(true);
            rol_btn_guardar_lbl.setVisible(false);
            rol_btn_guardar_lbl.setEnabled(false);
            rol_btn_guardar_lbl.setFocusable(false);
        } else {
            rol_btn_guardar_lbl_bloq.setVisible(false);
            rol_btn_guardar_lbl.setVisible(true);
            rol_btn_guardar_lbl.setEnabled(true);
            rol_btn_guardar_lbl.setFocusable(true);
        }
    }//GEN-LAST:event_rol_casilla_insertar_tfKeyReleased

    private void rol_btn_guardar_lbl_bloqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rol_btn_guardar_lbl_bloqMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rol_btn_guardar_lbl_bloqMouseEntered

    private void rol_btn_guardar_lbl_bloqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rol_btn_guardar_lbl_bloqMouseClicked
        Error err = new Error("Error, revisa los datos ingresados!", this, framep);
        err.setVisible(true);
    }//GEN-LAST:event_rol_btn_guardar_lbl_bloqMouseClicked

    private void rol_btn_guardar_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rol_btn_guardar_lblMouseClicked
        String nombrerol = rol_casilla_insertar_tf.getText();
        String[] args = new String[]{
            nombrerol
        };

        Object[] confirmar = new Object[]{"¿Crear Rol " + nombrerol + "?", this, table, 0, "agregar", "rol", args, framep};
        ConfirmarAccion conf = new ConfirmarAccion(confirmar, conn);
        conf.setVisible(true);
    }//GEN-LAST:event_rol_btn_guardar_lblMouseClicked

    private void editrol_btn_guardar_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editrol_btn_guardar_lblMouseClicked
        String rolnom = (String) table.getValueAt(table.getSelectedRow(), 0);
        int idrol = conn.obteneridRol(rolnom);
        String[] args = new String[]{
            editrol_casilla_insertar_tf.getText(),
            String.valueOf(idrol)
        };

        Object[] confirmar = new Object[]{"¿Editar Rol " + rolnom + "?", this, table, 0, "editar", "rol", args, framep};
        ConfirmarAccion conf = new ConfirmarAccion(confirmar, conn);
        conf.setVisible(true);

    }//GEN-LAST:event_editrol_btn_guardar_lblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roles(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit8;
    private javax.swing.JPanel editrol_btn_cancelar_pnl;
    private javax.swing.JLabel editrol_btn_caneclar_lbl;
    private javax.swing.JLabel editrol_btn_guardar_lbl;
    private javax.swing.JPanel editrol_btn_guardar_pnl;
    private javax.swing.JTextField editrol_casilla_insertar_tf;
    private javax.swing.JPanel editrol_contenedor_crear_pnl;
    private javax.swing.JSeparator editrol_separador_separa_spt;
    private javax.swing.JLabel editrol_subtitulo2_rolname_lbl;
    private javax.swing.JLabel editrol_subtitulo_detalle_lbl;
    private javax.swing.JLabel editrol_titulo_editar_lbl;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JPanel panelsup;
    private javax.swing.JPanel rol_btn_cancelar_pnl;
    private javax.swing.JLabel rol_btn_caneclar_lbl;
    private javax.swing.JLabel rol_btn_guardar_lbl;
    private javax.swing.JLabel rol_btn_guardar_lbl_bloq;
    private javax.swing.JPanel rol_btn_guardar_pnl;
    private javax.swing.JTextField rol_casilla_insertar_tf;
    private javax.swing.JPanel rol_editar_pnl;
    private javax.swing.JPanel rol_fondo_crear_pnl;
    private javax.swing.JPanel rol_fondo_principal_pnl;
    private javax.swing.JSeparator rol_separador_separa_spt;
    private javax.swing.JLabel rol_subtitulo3_rolname_lbl;
    private javax.swing.JLabel rol_subtitulo_detalle_lbl;
    private javax.swing.JLabel rol_titulo_crear_lbl;
    // End of variables declaration//GEN-END:variables
}
